application: previousnext/php5.5

# This will save on ECS resources, as well as provide a walled
# off memory allocation to ensure the lib doesn't not go over 128M.
config:
  mem_application: 128

channel: "#dashboard"

prepare: &prepare
  - composer install --prefer-dist --no-progress

test: &test
  - make lint-php

test_pr:
  setup: *prepare
  steps: *test

test_head:
  setup: *prepare
  steps: *test
