version: "3"

services:
  app:
    image: previousnext/php-apache:7.1-3.x-dev
    network_mode: host
    volumes:
      - .:/data
      - $HOME/.ssh:/root/.ssh
      - $HOME/.composer:/root/.composer
