# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
# Environment variables:
# Most environment variables are set at the org level.
version: 2

defaults: &defaults
  context: org-global

workflows:
  version: 2
  test:
    jobs:
    - test:
        <<: *defaults

jobs:
  test:
    docker:
    - image: previousnext/php-apache:7.1-3.x-dev
    working_directory: /data
    steps:
    - checkout
    - restore_cache:
        keys:
        - deps-{{ arch }}-{{ checksum "composer.lock" }}
    - run:
        name: "Setup: Dependencies"
        command: |
          make init
    - save_cache:
        key: deps-{{ arch }}-{{ checksum "composer.lock" }}
        paths:
        - /root/.composer
    - run:
        name: "Test: Lint"
        command: make lint-php
